#!/bin/bash
# Displays information about the file

file_path="school.txt"

if [ -e "$file_path" ]; then
    # Check if the file exists
    echo "school file exists"

    if [ -s "$file_path" ]; then
        # Check if the file is not empty
        echo "school file is not empty"

        if [ -f "$file_path" ]; then
            # Check if the file is a regular file
            echo "school file is a regular file"
        fi
    else
        echo "school file is empty"
    fi
else
    echo "school file does not exist"
fi
